version: '3'

services:
        nginx:
                image: nginx:latest
                container_name: nginx
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - /home/ubuntu/data//nginx:/etc/nginx/conf.d
                        - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
                        - /home/ubuntu/data/certbot/www:/var/www/certbot
                depends_on:
                        - certbot
                networks:
                        - local
        certbot:
                image: certbot/certbot
                volumes:
                        - /home/ubuntu/data/certbot/conf:/etc/letsencrypt
                        - /home/ubuntu/data/certbot/www:/var/www/certbot
                networks:
                        - local
        jenkins:
                image: jenkins/jenkins:lts 
                container_name: jenkins
                user: root
                ports:
                        - "8443:8080"
                volumes:
                        - /home/ubuntu/data/jenkins:/var/jenkins_home
                networks:
                        - local
                       
networks:
        local:
                driver: bridge
